services:
  database:
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "Teste123@"
    networks:
      app-network:
        aliases:
          - sql

  scheduler:
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    ports:
      - "5125:8080"
    depends_on:
      - database
    networks:
      - app-network

networks:
  app-network:
    driver: bridge